---
- name: Setup web server
  hosts: local
  become: yes   # use sudo
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Create custom index page
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <h1>Hello from Ansible 🚀</h1>
          <p>Deployed automatically at {{ ansible_date_time.iso8601 }}</p>

