---
# ======================================================
# PLAY 1: Common setup for all Kubernetes nodes
# ======================================================
- name: Prepare all Kubernetes nodes
  hosts: k8s_cluster
  become: yes

  tasks:
    - name: Disable swap now
      ansible.builtin.command: swapoff -a
      when: ansible_swaptotal_mb | int > 0

    - name: Disable swap permanently
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '(^.*\sswap\s+sw\s+.*$)'
        replace: '# \1'

    - name: Load kernel modules config
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
      notify: Load k8s modules

    - name: Set sysctl params for Kubernetes
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
      notify: Reload sysctl

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    # -------- Install containerd ----------
    - name: Install containerd
      ansible.builtin.apt:
        name: containerd
        state: present

    - name: Create containerd config directory
      ansible.builtin.file:
        path: /etc/containerd
        state: directory

    - name: Generate default containerd config
      ansible.builtin.command: containerd config default
      register: containerd_config
      changed_when: false

    - name: Write containerd config file
      ansible.builtin.copy:
        dest: /etc/containerd/config.toml
        content: "{{ containerd_config.stdout }}"
      notify: Restart containerd

    - name: Set SystemdCgroup = true in containerd
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'
      notify: Restart containerd

    - name: Ensure containerd is enabled and running
      ansible.builtin.service:
        name: containerd
        state: started
        enabled: yes

    # -------- Install kubeadm / kubelet / kubectl ----------
    - name: Ensure kubernetes keyring directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes apt key (new repo format)
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        dest: /tmp/kubernetes-release.key
        mode: '0644'
        timeout: 30

    - name: Convert Kubernetes key to keyring
      ansible.builtin.command: >
        gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg /tmp/kubernetes-release.key
      args:
        creates: /etc/apt/keyrings/kubernetes-archive-keyring.gpg

    - name: Add Kubernetes apt repository (new repo format)
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
        state: present
        filename: kubernetes

    - name: Install kubeadm, kubelet, kubectl
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold kube packages at current version
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

  handlers:
    - name: Load k8s modules
      ansible.builtin.shell: |
        modprobe overlay
        modprobe br_netfilter

    - name: Reload sysctl
      ansible.builtin.command: sysctl --system

    - name: Restart containerd
      ansible.builtin.service:
        name: containerd
        state: restarted


# ======================================================
# PLAY 2: Initialize Kubernetes control-plane
# ======================================================
- name: Initialize Kubernetes control-plane
  hosts: k8s_master
  become: yes

  vars:
    pod_network_cidr: "10.244.0.0/16"

  tasks:
    - name: Run kubeadm init (idempotent)
      ansible.builtin.command: >
        kubeadm init
        --pod-network-cidr={{ pod_network_cidr }}
        --cri-socket=unix:///run/containerd/containerd.sock
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init

    - name: Create .kube directory for user
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy admin.conf to user kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'

    - name: Get join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: k8s_join_command
      changed_when: false


# ======================================================
# PLAY 3: Join worker nodes to the cluster
# ======================================================
- name: Join worker nodes to cluster
  hosts: k8s_workers
  become: yes

  tasks:
    - name: Check if kubelet.conf already exists
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Join node to Kubernetes cluster
      ansible.builtin.shell: >
        {{ hostvars[groups['k8s_master'][0]].k8s_join_command.stdout }}
        --cri-socket=unix:///run/containerd/containerd.sock
      when: not kubelet_conf.stat.exists
